name: Unzip ChioriyaApp.zip

on:
  push:
    paths:
      - client.zip
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip the project
        run: |
          unzip client.zip -d temp
          mv temp/* .
          rm -rf temp client.zip

      - name: Commit extracted files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Auto-extracted client.zip"
          git push
